---
name: Bug Report
description: Report a bug in the project
labels: ["bug"]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Describe the bug that you are experiencing, including what you expected to happen
    validations:
      required: true

  - type: textarea
    id: externaldns-configuration
    attributes:
      label: ExternalDNS Configuration
      description: |
        Configuration of ExternalDNS that you are using (e.g. Helm Values, Kubernetes manifests, etc)
      placeholder: |
        ```yaml
        Paste your configuation here
        ```
    validations:
      required: true

  - type: textarea
    id: externaldns-logs
    attributes:
      label: ExternalDNS Logs
      description: |
        Logs (be sure to enable debug logging on ExternalDNS)
      placeholder: |
        ```text
        Paste your ExternalDNS logs here
        ```
    validations:
      required: true

  - type: textarea
    id: webhook-logs
    attributes:
      label: Webhook Logs
      description: |
        Logs (be sure to enable debug logging on this Webhook)
      placeholder: |
        ```text
        Paste your Webhook logs here
        ```
    validations:
      required: true

  - type: input
    id: unifios-version
    attributes:
      label: PiHole version
      description: Version of PiHole that you are using
      placeholder: e.g. 6.0.1
    validations:
      required: true

  - type: input
    id: externaldns-version
    attributes:
      label: ExternalDNS Version
      description: Version of ExternalDNS that you are using
      placeholder: e.g. 0.14.2
    validations:
      required: true

  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I have searched the open and closed issues for duplicates
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/tarantini-io/external-dns-pihole-webhook/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
